Set PRIVATE_BUILD_DESC to space separated string
PRIVATE_BUILD_DESC needs to be space separated, otherwise we cannot
sign our ROMs, it fails with:

  Traceback (most recent call last):
    File "./build/tools/releasetools/sign_target_files_apks", line 895, in <module>
      main(sys.argv[1:])
    File "./build/tools/releasetools/sign_target_files_apks", line 876, in main
      compressed_extension)
    File "./build/tools/releasetools/sign_target_files_apks", line 291, in ProcessTargetFiles
      new_data = RewriteProps(data)
    File "./build/tools/releasetools/sign_target_files_apks", line 468, in RewriteProps
      assert len(pieces) == 5
  AssertionError
  Traceback (most recent call last):
    File "./build/tools/releasetools/ota_from_target_files", line 2051, in <module>
      main(sys.argv[1:])
    File "./build/tools/releasetools/ota_from_target_files", line 1939, in main
      OPTIONS.info_dict = common.LoadInfoDict(input_zip)
    File "/android/lineage-16.0/build/make/tools/releasetools/common.py", line 169, in LoadInfoDict
      raise ValueError("can't find META/misc_info.txt in input target-files")
  ValueError: can't find META/misc_info.txt in input target-files

where "pieces" is obtained by splitting build description on
spaces (see sign_target_files_apks.py).

Change-Id: If744b72ef36be4eb8a598bf43544055f38b8315c